# Generated by Django 3.0.2 on 2020-01-13 22:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_auto_20200113_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=3, verbose_name='State')),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='CFRequestId',
            new_name='cf_request_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='RequestDate',
            new_name='request_date',
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateTimeField()),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ssn', models.IntegerField()),
                ('home_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('tax_id', models.IntegerField(verbose_name='TaxID')),
                ('annual_revenue', models.FloatField(verbose_name='AnnualRevenue')),
                ('monthly_average_balance', models.FloatField(verbose_name='MonthlyAverageBankBalance')),
                ('monthly_average_credit_card_volume', models.FloatField(verbose_name='MonthlyAverageCreditCardVolume')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('naics', models.IntegerField(verbose_name='NAICS')),
                ('has_been_profitable', models.BooleanField(verbose_name='HasBeenProfitable')),
                ('has_bunkrupted', models.BooleanField(verbose_name='HasBankruptedInLast7Years')),
                ('inception_date', models.DateTimeField(verbose_name='InceptionDate')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.Address')),
            ],
        ),
    ]
