# Generated by Django 3.0.2 on 2020-01-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_auto_20200113_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(to='loanapp.Owner'),
        ),
        migrations.AddField(
            model_name='business',
            name='owners_percentage',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
