# Generated by Django 3.0.2 on 2020-01-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_auto_20200113_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owners_percentage',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=1, max_length=3, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loanapp.Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='cf_api_password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='cf_api_user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='filter_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='is_test_lead',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='legal_entity_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='owners',
            field=models.ManyToManyField(to='loanapp.Owner'),
        ),
        migrations.AddField(
            model_name='application',
            name='owners_percentage',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='request_load_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='stated_credit_history',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
