# Generated by Django 3.0.2 on 2020-01-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_auto_20200113_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='submitted', max_length=10),
        ),
    ]
