# Generated by Django 3.0.2 on 2020-01-14 11:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0008_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='cf_api_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cf_api_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='owners_percentage',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='annual_revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='has_been_profitable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='has_bunkrupted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='inception_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='monthly_average_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='monthly_average_credit_card_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='naics',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
