# Generated by Django 3.0.2 on 2020-01-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0009_auto_20200114_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='processing', max_length=10),
        ),
    ]
